### ISSUE TITLE
[Android]Confirm and reject button has incorrect status( enabled) if more confirmations are required but no more imported owners

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1386]
**Describe the bug**
The confirmation button is not disabled after tx confirmation and the reject button status is changed from disabled to enabled after tx confirmation if more confirmations are required but no more imported owner keys
The confirm button status is not updated to the correct if more confirmations are required but there is no more imported owners

**To Reproduce**
1st case :Steps to reproduce the behavior:
Precondition:
0. Sfe with 3 or more required confirmation
1. Create tx and reject it as owner 1 
2. import owner 2 key to the mobile app

Steps
1. Go to Queue
2. Open transaction details for tx from the precondition
Current result: reject button is disabled and Confirm is enabled

3. Click confirm and select owner to confirm tx
Current result: The tx is confirmed message appears but the Confirm button is not disabled

4. Click Confirm again
Current result: Select owner to confirm screen is opened. The list is empty

5. Go back
Current result: Confirm button disappears but Reject button is enabled instead of disabled. The user can reject tx and his signature will be saved to the cancellation tx

2nd case:
Precondition"
1. safe with 3 required confirmation
2. owner 1 creates transaction and rejects the transaction
3. Owner 2 imported to the mobile app

Steps:
1. go to the cancellation tx details and click Confirm button
Current result: The signing from the owner 2 is saved but the Confirm button is still available.

**Expected behavior**
The correct state of the buttons should be used
1. both buttons should be disabled if the tx was confirmed and cancellation tx exists when more confirmations are required but no more imported owners
2. Disabled state of the reject button should not be changed to enabled if cancellation tx exists

**Video**
https://drive.google.com/file/d/1OWmjgipdXKHo1FnIG2J7AKB4Uiknz-Jr/view?usp=sharing

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.14.0 - 2417rc

**Environment**
staging, rinkeby
**Additional context**

**Comment by tschubotz** [comment]
hmm, tough one. `critical` or `major`. I'd lean towards marking as `major`, i.e. not blocking the current release since while being inconvenient, nothing bad happens and it's quite a special case. What do you think? @liliya-soroka @gnosis/android

If not in the current release, I think this should be fixed in the "New York" sprint then.

**Comment by liliya-soroka** [comment]
My opinion: Confusing for the user, as the buttons are enabled when should not. But not a blocker for the user, as either empty "select owners" screen is displayed or the signature is saved without duplication on UI.
I prefer to include it as a must in the 2.15.0 , as it will be a case for any safe with more than 2 required confirmations

**Comment by biafra23** [comment]
Just to clarify. This problem does not occur, when the three keys have been imported from the start? It is only a problem when the second key is imported in step  2?

**Comment by liliya-soroka** [comment]
Reopened**( not critical for release)**:
the first case is not fixed fully:
Precondition:
1. safe with threshold>=3
2. import owner 1
3. owner 2 creates a transaction on the web and cancelled it

Steps:
1. Imported owner opens transaction details for the original transaction 
The reject button is disabled for him as the cancellation tx exist
2. Click Confirm and select imported owner
Current result: after confirmation the confirm button disappears but the reject button becomes active and red instead of grey 


app version 2.14.0 - 2434rc

**Comment by liliya-soroka** [comment]
Verified
app version 2.14.0 -2479
